### ISSUE TITLE
Nnative breakpoints do not work

### ISSUE THREAD

**Issue by screwer** [Microsoft/MIEngine#403]
I create app with wizard template "Native-Activity Application (Android)". Compile it as x86, set some breakpoints into 'android_main' and run debug. App was sucessfully deployed into emulator and runs. But breakpoints do not hits, and in breakpoints window appears with empty circles.

**Environment:**
Visual Studio 2015
CrossPlatform installed. Also i tried to checkout and run MSIEnine project with the same effect.

**Emulator:**
BlueStacks 2.1.8.5663

_shell@klte:/ $ getprop ro.build.version.release
4.4.2
shell@klte:/ $ getprop ro.build.version.sdk
19
shell@klte:/ $ cat /proc/version
Linux version 3.10.30-android-hd (build@Build2) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #1 PREEMPT Tue Mar 22 19:05:48 IST 2016_

**Build log:**
1>------ Rebuild All started: Project: Android2.NativeActivity, Configuration: Debug x86 ------
1>  ANDROID_HOME=E:\Android\sdk
1>  ANT_HOME=E:\Android\ant-1.9.7
1>  JAVA_HOME=C:\Program Files (x86)\Java\jdk1.8.0_101
1>  NDK_ROOT=E:\Android\ndk\android-ndk-r11c
1>  pch.h
1>  android_native_app_glue.c
1>  main.cpp
1>  Android2.NativeActivity.vcxproj -> c:\Work\test\Android2\x86\Debug\libAndroid2.so

**Debug session (with the 'Break All' at end:**

Due to its size moved to "paste" service: http://pasted.co/60c83004

**Comment by paulmaybee** [comment]
Looking at the log I see no breakpoints being set. If you hover the cursor over one of the “empty circles” do you get a pop-up with a message? What is reported?

**Comment by rick111111** [comment]
From the log it looks MIEngine haven't even made the attempt to set the breakpoints. Are you running MIEngine bits by launching from MIEngine.sln?

Could you try without launching from MIEngine.sln, and only use the bits installed. and save a log as mentioned in https://github.com/Microsoft/MIEngine/wiki/Logging?

**Comment by faxue-msft** [comment]
From the log it looks MIEngine haven't even made the attempt to set the breakpoints. Are you running MIEngine bits by launching from MIEngine.sln?

Could you try without launching from MIEngine.sln, and only use the bits installed. and save a log as mentioned in https://github.com/Microsoft/MIEngine/wiki/Logging?

**Comment by screwer** [comment]
**To faxue-msft:**
I'm tried to debug w/ and w/o MIEngine, issue exists in both cases. Yes, you right. Log i post previous is taken from MIEngine launched. There is log from ordinary started VS: http://pasted.co/7a8a2911

It's my home computer with the same issue. Differences in operating system (Win10 now, Win7 earlies) and NDK version (12b now, 11c earlier). 

**To paulmaybee:** 
Text in tooltip:
"The breakpoint will not currently be hit. Module containing this breakpoint has not yet loaded or the breakpoint could not be obtained.

Location: man.cpp, line 225 ('android_main(struct android_app* state)')

Screenshot: http://storage8.static.itmages.com/i/16/0803/h_1470253431_3943170_3331adced7.png

Also i try to set breakpoint on LOGI accelerometer with the same effect.

*UPDATE:*
After reproduce and capture log+sshot and write this text (that taken some time) i stop debug and exeption appears:

---------------------------
Microsoft Visual Studio
---------------------------
Error while trying to enter break state. Debugging will now stop. Internal error in MIEngine. Exception of type 'System.NullReferenceException' was thrown.

   at Microsoft.MIDebugEngine.ThreadCache.<GetThreadContext>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.MIDebugEngine.DebuggedProcess.<HandleBreakModeEvent>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.MIDebugEngine.DebuggedProcess.<<-ctor>b__53_7>d.MoveNext()
---------------------------
OK   
---------------------------

**Comment by faxue-msft** [comment]
The assert/exception you saw on stop debugging is a known issue and has been fixed in latest MIEngine (at https://github.com/Microsoft/MIEngine/commit/bdc768a84ec7df3921a6c7c9b597b034d2aad15e)

**Comment by faxue-msft** [comment]
The log shows that debugger made no attempt to set a breakpoint, I suspect this may have something to do with the emulator you are using, have you ever tried Microsoft Android Emulator and see whether it works? (https://www.visualstudio.com/en-us/features/msft-android-emulator-vs.aspx)

**Comment by screwer** [comment]
I cannot use Microsoft emulator, because CPU is core2 and not supported by modern hyper-v.

Android studio Java debugging works well with Bluestacks.

I can try google emulator from SDK tommorow.

**Comment by gregg-miskelly** [comment]
@screwer just to be clear - don't try Goggle's ARM emulator -- that emulator doesn't correctly emulate breakpoints and so debugging doesn't work at all. Their x86/x64 emulator may be fine.

**Comment by screwer** [comment]
@Gregg Miskelly: bas new about Google ARM. If this helps - VisualGDB extension can handle BPs on it. This extension also has few workarounds on Google's bugs, as far i know.

I'll try all cases, but few days later.

**Comment by screwer** [comment]
I check dozen real devices and breakpoints works well. Seems to be an emulator issue.
